"""ERA5 VPM band series -- run this INSIDE GCP (Colab, or a VM in the bucket's region).

GENERATED by `ts-mjo/make_colab_bundle.py` from `velocity_potential.py` and
`era5_vpm_clim.py`. Do not edit here; edit those and regenerate.

Why in-cloud: the reduction is 0.1% of wall clock and the transfer is 85%, at a
measured 1.4 MB/s that does not improve with concurrency. Inside GCP the same
read is hundreds of MB/s, so the 30-year job goes from ~12 h to minutes and only
the ~38 MB of reduced band series travels back.

Because bandwidth stops being the constraint, this defaults to STRIDE = 1 -- a
*contiguous daily* series. That is strictly more than the local run can afford,
and it is what the two remaining pieces need: the 120-day low-frequency filter
(MJO_PHASE.md 4.3) requires unbroken daily history, and so does building a VPM
EOF basis. The local stride-2 run can only ever yield the climatology.

Colab:  paste this in a cell, run it, then download the zip it writes.
"""
import numpy as np, datetime as dt, time, os, sys

N_LON_BINS = 144
LAT_BAND = 15.0
FIELDS = ("chi200", "u850", "u200")
ARCO = ("https://storage.googleapis.com/gcp-public-data-arco-era5/ar/"
        "1959-2022-6h-240x121_equiangular_with_poles_conservative.zarr")

Y0, Y1 = 1991, 2020          # WMO standard normal; 1979-2021 is equally feasible here
STRIDE = 1                    # contiguous daily -- see the note above
BLOCK  = 480                  # bigger blocks inside GCP; the link is no longer the limit
OUTDIR = "era5_vpm"


import numpy as np
from scipy.linalg import solve_banded

EARTH_RADIUS = 6371229.0    # m, IFS value


def velocity_potential(u, v, lat, lon):
    """`chi` [m^2/s] from a horizontal wind field on a regular lat/lon grid.

    Parameters
    ----------
    u, v : (..., nlat, nlon)
        Wind components. Leading axes are looped over, so a whole
        (member, time) stack can be passed at once.
    lat : (nlat,)
        Latitudes in degrees, at cell centres, monotonic. Either direction.
    lon : (nlon,)
        Longitudes in degrees, evenly spaced, spanning 360 (periodic).

    Returns
    -------
    (..., nlat, nlon) with the area-weighted mean removed on each field.
    """
    lat = np.asarray(lat, dtype=np.float64)
    flip = lat[0] > lat[-1]
    if flip:                                  # solver wants increasing latitude
        lat = lat[::-1]
        u, v = u[..., ::-1, :], v[..., ::-1, :]

    d = divergence_latlon(u, v, lat, lon)
    chi = solve_poisson_sphere(d, lat, lon)
    return chi[..., ::-1, :] if flip else chi


def divergence_latlon(u, v, lat, lon):
    """Horizontal divergence on a regular lat/lon grid.

        D = 1/(a cos(phi)) * [ du/dlambda + d(v cos(phi))/dphi ]

    Centred differences: exact and periodic in longitude via `np.roll`; the
    meridional term differentiates `v cos(phi)` as a product, so the metric term
    is carried rather than dropped.
    """
    lat = np.asarray(lat, dtype=np.float64)
    phi = np.deg2rad(lat)
    cosphi = np.cos(phi)
    dlam = np.deg2rad(float(lon[1] - lon[0]))
    dphi = float(phi[1] - phi[0])

    du = (np.roll(u, -1, axis=-1) - np.roll(u, 1, axis=-1)) / (2.0 * dlam)

    vcos = v * cosphi[:, None]
    dvcos = np.empty_like(vcos)
    dvcos[..., 1:-1, :] = (vcos[..., 2:, :] - vcos[..., :-2, :]) / (2.0 * dphi)
    # One-sided at the first/last row. v*cos(phi) -> 0 at the poles, so the
    # rows just inside them carry a small residual either way; the +-15 deg band
    # VPM uses is 75 deg away and cannot see it.
    dvcos[..., 0, :] = (vcos[..., 1, :] - vcos[..., 0, :]) / dphi
    dvcos[..., -1, :] = (vcos[..., -1, :] - vcos[..., -2, :]) / dphi

    return (du + dvcos) / (EARTH_RADIUS * cosphi[:, None])


def solve_poisson_sphere(d, lat, lon):
    """Solve `laplacian(chi) = d` on the sphere. See the module docstring."""
    lat = np.asarray(lat, dtype=np.float64)
    phi = np.deg2rad(lat)
    nlat, nlon = d.shape[-2], d.shape[-1]
    dphi = float(phi[1] - phi[0])
    cosphi = np.cos(phi)

    # cos(phi) at the half levels; zero at the poles gives no-flux for free
    ph = np.empty(nlat + 1)
    ph[1:-1] = 0.5 * (phi[:-1] + phi[1:])
    ph[0], ph[-1] = phi[0] - 0.5 * dphi, phi[-1] + 0.5 * dphi
    cos_h = np.clip(np.cos(ph), 0.0, None)
    lower_c, upper_c = cos_h[:-1] / dphi**2, cos_h[1:] / dphi**2

    lead = d.shape[:-2]
    dflat = d.reshape(-1, nlat, nlon)
    dm = np.fft.rfft(dflat, axis=-1)                 # exact: periodic in lambda
    m = np.arange(dm.shape[-1])
    chim = np.empty_like(dm)

    for k, mk in enumerate(m):
        ab = np.zeros((3, nlat))
        ab[0, 1:] = upper_c[:-1]                     # super-diagonal
        ab[2, :-1] = lower_c[1:]                     # sub-diagonal
        ab[1, :] = -(lower_c + upper_c) - (mk**2) / cosphi
        rhs = (EARTH_RADIUS**2 * cosphi)[None, :] * dm[:, :, k]
        if mk == 0:
            # singular: chi defined up to a constant. Pin one row.
            ab[1, 0], ab[0, 1] = 1.0, 0.0
            rhs = rhs.copy()
            rhs[:, 0] = 0.0
        chim[:, :, k] = (solve_banded((1, 1), ab, rhs.real.T).T
                         + 1j * solve_banded((1, 1), ab, rhs.imag.T).T)

    chi = np.fft.irfft(chim, n=nlon, axis=-1)
    w = np.broadcast_to(cosphi[:, None], (nlat, nlon))
    chi -= (chi * w).sum(axis=(-2, -1), keepdims=True) / w.sum()
    return chi.reshape(*lead, nlat, nlon)


def band_mean(field, lat, lon180, lat_band=LAT_BAND, nbins=N_LON_BINS):
    """(nt, nlat, nlon) -> (nt, 144) cosine-weighted mean over +-lat_band.

    Same reduction as `mjo_index.meridional_band`, but on a regular grid the
    latitude weights are shared by every longitude, so it is a plain tensor
    contraction rather than a bincount.
    """
    m = np.abs(lat) <= lat_band
    w = np.cos(np.deg2rad(lat[m]))
    b = np.einsum("tij,i->tj", field[:, m, :], w) / w.sum()   # (nt, nlon)
    idx = np.clip(np.floor((lon180 + 180.0) / (360.0 / nbins)).astype(int), 0, nbins - 1)
    cnt = np.bincount(idx, minlength=nbins)
    out = np.stack([np.bincount(idx, weights=b[t], minlength=nbins) for t in range(b.shape[0])])
    return out / np.maximum(cnt, 1)[None, :]


def open_era5():
    import xarray as xr
    ds = xr.open_zarr(ARCO, chunks=None, consolidated=True)
    lat = ds.latitude.values.astype(float)            # -90..90 increasing
    lon = ds.longitude.values.astype(float)           # 0..358.5
    lon180 = np.where(lon > 180.0, lon - 360.0, lon)
    return ds, lat, lon, lon180


def bands_for_slice(ds, sl, lat, lon, lon180):
    """Band series for a time slice -> dict of (nt, 144)."""
    sub = ds[["u_component_of_wind", "v_component_of_wind"]].isel(time=sl)
    # Read each variable ONCE and slice levels in memory. The store chunks all 13
    # levels together, so `.sel(level=200)` and `.sel(level=850)` on the same
    # variable fetch the *same* chunks twice over the network -- 50% extra
    # transfer on u, 33% on the job, which on a ~17 h stream is hours.
    lev = list(ds.level.values)
    i200, i850 = lev.index(200), lev.index(850)
    # stored as (time, level, longitude, latitude); the solver wants (t, lat, lon)
    uu = sub.u_component_of_wind.values
    vv = sub.v_component_of_wind.values
    u2 = uu[:, i200].transpose(0, 2, 1)
    u8 = uu[:, i850].transpose(0, 2, 1)
    v2 = vv[:, i200].transpose(0, 2, 1)
    del uu, vv

    d = divergence_latlon(u2, v2, lat, lon)
    chi = solve_poisson_sphere(d, lat, lon)
    return {"chi200": band_mean(chi, lat, lon180),
            "u850": band_mean(u8, lat, lon180),
            "u200": band_mean(u2, lat, lon180)}


def daily(bands, times):
    """6-hourly (nt,144) -> daily (nd,144) plus the dates."""
    days = np.array([np.datetime64(t, "D") for t in times])
    uniq = np.unique(days)
    out = {k: np.stack([v[days == d].mean(axis=0) for d in uniq]) for k, v in bands.items()}
    return out, uniq


def main():
    os.makedirs(OUTDIR, exist_ok=True)
    ds, lat, lon, lon180 = open_era5()
    t = ds.time.values
    for y in range(Y0, Y1 + 1):
        out = f"{OUTDIR}/era5_vpm_{y}.npz"
        if os.path.exists(out):
            print(f"skip {y}"); continue
        sel = np.where((t >= np.datetime64(f"{y}-01-01")) &
                       (t <  np.datetime64(f"{y+1}-01-01")))[0]
        i0, i1 = int(sel[0]), int(sel[-1]) + 1
        acc, dates_all, t0 = [], [], time.time()
        for a in range(i0, i1, BLOCK * STRIDE):
            b = min(a + BLOCK, i1)
            bands = bands_for_slice(ds, slice(a, b), lat, lon, lon180)
            d, dd = daily(bands, t[a:b])
            acc.append(d); dates_all.append(dd)
        dates = np.concatenate(dates_all)
        series = {k: np.concatenate([x[k] for x in acc]) for k in FIELDS}
        np.savez(out, dates=dates.astype("datetime64[D]").astype(str), **series)
        print(f"{y}: {len(dates)} days in {time.time()-t0:.0f}s -> {out}", flush=True)

    import shutil
    z = shutil.make_archive("era5_vpm_bands", "zip", OUTDIR)
    print(f"\nwrote {z} ({os.path.getsize(z)/1e6:.1f} MB)")
    print("Download it, drop the .npz files in /tank/projects/era5_vpm_clim/,")
    print("then:  python era5_vpm_clim.py --mode combine \\")
    print("           --inputs /tank/projects/era5_vpm_clim/era5_vpm_????.npz \\")
    print("           --harmonics 3 --out .../vpm_clim_1991_2020.npz")


if __name__ == "__main__":
    main()
