"""Emit a self-contained ERA5 VPM extractor to run *inside* GCP (Colab or a VM).

Why this exists
---------------
The extraction is not compute-bound and a cluster does not help. Measured on
this box, for one 80-step block:

    divergence     0.09 s
    Poisson solve  0.08 s
    band mean      0.00 s      -> 2 ms/step, 0.1% of wall clock
    transfer       148 s       -> 85% of wall clock, at a hard 1.4 MB/s

and 8, 16 and 32 concurrent readers all returned the same 1.4 MB/s, so the
limit is the link out of this building, not latency and not cores. Adding
workers here multiplies a resource that is already 99.9% idle.

The one lever that works is to run the reduction where the bytes already are.
ARCO-ERA5 lives in GCS, so compute inside GCP reads it at hundreds of MB/s and
only the *reduced* product - a few tens of MB of band series - comes back over
the slow link. Same code, same answer, transfer reduced by ~1500x.

This script is GENERATED from the repo sources rather than written by hand, so
the cloud copy cannot drift from the local one. `velocity_potential.py` is
embedded verbatim; the reduction functions are lifted from `era5_vpm_clim.py`.
Regenerate with `python make_colab_bundle.py` whenever either changes.
"""
import inspect, pathlib, textwrap

import era5_vpm_clim as E

HERE = pathlib.Path(__file__).parent
vp = (HERE / "velocity_potential.py").read_text()
# keep the solver and the divergence, drop the module docstring's duplication
vp_body = vp[vp.index("from __future__"):]

parts = [inspect.getsource(f) for f in (E.band_mean, E.open_era5,
                                        E.bands_for_slice, E.daily)]

HEADER = '''"""ERA5 VPM band series -- run this INSIDE GCP (Colab, or a VM in the bucket's region).

GENERATED by `ts-mjo/make_colab_bundle.py` from `velocity_potential.py` and
`era5_vpm_clim.py`. Do not edit here; edit those and regenerate.

Why in-cloud: the reduction is 0.1% of wall clock and the transfer is 85%, at a
measured 1.4 MB/s that does not improve with concurrency. Inside GCP the same
read is hundreds of MB/s, so the 30-year job goes from ~12 h to minutes and only
the ~38 MB of reduced band series travels back.

Because bandwidth stops being the constraint, this defaults to STRIDE = 1 -- a
*contiguous daily* series. That is strictly more than the local run can afford,
and it is what the two remaining pieces need: the 120-day low-frequency filter
(MJO_PHASE.md 4.3) requires unbroken daily history, and so does building a VPM
EOF basis. The local stride-2 run can only ever yield the climatology.

Colab:  paste this in a cell, run it, then download the zip it writes.
"""
import numpy as np, datetime as dt, time, os, sys

N_LON_BINS = 144
LAT_BAND = 15.0
FIELDS = ("chi200", "u850", "u200")
ARCO = ("https://storage.googleapis.com/gcp-public-data-arco-era5/ar/"
        "1959-2022-6h-240x121_equiangular_with_poles_conservative.zarr")

Y0, Y1 = 1991, 2020          # WMO standard normal; 1979-2021 is equally feasible here
STRIDE = 1                    # contiguous daily -- see the note above
BLOCK  = 480                  # bigger blocks inside GCP; the link is no longer the limit
OUTDIR = "era5_vpm"

'''

FOOTER = '''

def main():
    os.makedirs(OUTDIR, exist_ok=True)
    ds, lat, lon, lon180 = open_era5()
    t = ds.time.values
    for y in range(Y0, Y1 + 1):
        out = f"{OUTDIR}/era5_vpm_{y}.npz"
        if os.path.exists(out):
            print(f"skip {y}"); continue
        sel = np.where((t >= np.datetime64(f"{y}-01-01")) &
                       (t <  np.datetime64(f"{y+1}-01-01")))[0]
        i0, i1 = int(sel[0]), int(sel[-1]) + 1
        acc, dates_all, t0 = [], [], time.time()
        for a in range(i0, i1, BLOCK * STRIDE):
            b = min(a + BLOCK, i1)
            bands = bands_for_slice(ds, slice(a, b), lat, lon, lon180)
            d, dd = daily(bands, t[a:b])
            acc.append(d); dates_all.append(dd)
        dates = np.concatenate(dates_all)
        series = {k: np.concatenate([x[k] for x in acc]) for k in FIELDS}
        np.savez(out, dates=dates.astype("datetime64[D]").astype(str), **series)
        print(f"{y}: {len(dates)} days in {time.time()-t0:.0f}s -> {out}", flush=True)

    import shutil
    z = shutil.make_archive("era5_vpm_bands", "zip", OUTDIR)
    print(f"\\nwrote {z} ({os.path.getsize(z)/1e6:.1f} MB)")
    print("Download it, drop the .npz files in /tank/projects/era5_vpm_clim/,")
    print("then:  python era5_vpm_clim.py --mode combine \\\\")
    print("           --inputs /tank/projects/era5_vpm_clim/era5_vpm_????.npz \\\\")
    print("           --harmonics 3 --out .../vpm_clim_1991_2020.npz")


if __name__ == "__main__":
    main()
'''

out = HEADER + vp_body.replace("from __future__ import annotations\n", "") \
      + "\n\n" + "\n\n".join(parts) + FOOTER
(HERE / "era5_vpm_colab.py").write_text(out)
print(f"wrote era5_vpm_colab.py ({len(out.splitlines())} lines)")
